{% set name = "staticjinja" %}
{% set version = "0.3.4" %}
{% set sha256 = "62803c2369bf148213744c5797c4a2a5820061fc0bf6d4bbaba79832bc3fbbd7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - staticjinja = staticjinja.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docopt
    - easywatch
    - jinja2

test:
  imports:
    - staticjinja
  commands:
    - staticjinja --help

about:
  home: http://github.com/Ceasar/staticjinja
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'jinja based static site generator'
  description: |
    staticjinja is a library for easily deploying static sites using the Jinja2
    template engine.

    Most static site generators are cumbersome to use. Nevertheless, when
    deploying a static website that could benefit from factored out data or
    modular html pages (especially convenient when prototyping), a templating
    engine can be invaluable. Jinja2 is an extremely powerful tool in this
    regard.

    staticjinja is designed to be lightweight, easy-to-use, and highly
    extensible, enabling you to focus on simply making your site.
  dev_url: http://github.com/Ceasar/staticjinja

extra:
  recipe-maintainers:
    - dougalsutherland
