travis:
  secure:
    BINSTAR_TOKEN: FVE4zPMbJoRSNqimq2jTKT5BMH5y5ms1/ZcG0bgTREsVm4gnMwQ8EawV3hidJ4POzku88sS+DO486VWNE4W7E5cNMileK2un9BoDIJNI69NSEwq12B/V7+sok9NXigkvtE4eov7gdI+uKxetiLZQx2WVsKTakMixBMDNP22r6YL7UYAl14FmnxjaQBm/vx+mVpX3NJJerhtkD6Uyo/2+poIiDgeu0EKrb8Xt6Jx6z9CuyQ+FNlDEvcgdWFKWTciTlPRCAjI16fg7RnWqrUVVQI5qpNXM2nXnLzkpZj+0PMH0inWKzEfBiKcUN3qJFkMjEp6eMZidcCuynDDTixllpVuphvPF48XoJoZg6z2UmkV8V0EoRIkc43cw3Lw4NoGvSRLG6pf37VPRHpWMJbufK16aoiCcmCsL9qWecPjviC+G9IqO6mBs+dY+LX05iUgSzlQmpFN/3i7y8kzOBIu4A3fyb8jk0k3XKpp3qmg6kSSfM7jjBs3qP4KP23tNE4CfB8vavyiPuH7wNWGY6Zv2F23H4u5r1DR0heKcem7VsrcM6/IPTjRw8hmLLJQAGujh2ymYYJArWtieFsNMh13x1+Ph+rEIV3sEdnFkrh3wu5qMJRBHn2Tp8bFixr6bniEZEUTaRmpextz5hFD4BZudIehfpjQrGOdAXiuyygkzXvg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
