travis:
  secure:
    BINSTAR_TOKEN: J0CcKOgr0OMFRAOTEGDHmFGpxwK3yMqVe+UwsNz4JPOTGl8h9wF5172nFZun1qNZf3dpRR26rvHe16DeyO9e39O/aG4V9GEUr/EBTFtg9IhjjPrmE9wB0GPqofC45xDDJD1UjEhMJQjvRjHcJjvFL5ZTl815vR6nhPbEtsvLL/tZkMTtz3fWAlflsnx/lsNZlH1LlwqbQDiXnEY+zmiag90W8K7TmEqArIGoSyG/h7xt8BINfX14yGhqp25QNlijo+m9qZjSVOBdsPU5q1knP/lpULmWcayALBLEmNqvB7wV4vjdVXXPVJbf0kuWDgSxJRgXdz5LM4IDyjsV5lDkLJ3QKLcBxJ+SPkZysHfTZ/iE5aBVnW7b1H8jSFcg1tVsqX5WptVB1cU9btShSvfD/dNAJ4DufnLveayHuClsjJOXr6aD4Pxzu9udgnOygZeuyQZnVRZ2c6Dt/6nwTFiiGtpHMxKzQt/UzuDYaUff6DYSANo54PrQ205KcaRd7jRWKUcfZGDfX8tPb+zdy+cf3jDRuYSLQkyk4RbXslB7zex/wVUVv061byXWhlma6yhKhvJ2L8cp+QAvMPHa8FHouF2yzZ1PR1vyGYKJ6cKEr8SzYyGl9WuUSrnkm7nQvL7KJXXMhlbZofQSDa5+G2VaF4S2xhnipjg73yXP7DNWkZU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
